# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 14, 16 ]

    runs-on: ${{ matrix.os }}

    steps:
      - if: contains(matrix.os, 'windows')
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint
      - run: sudo chmod -R 777 ./dist
        if: contains(matrix.os, 'windows') == false
      - run: yarn build
      - run: yarn test
        env:
          CI: true
